'use client';

import { useEffect, useMemo, useState } from 'react';

const questions = [
  { id:'q1', category:'GOAL', text:'เป้าหมายหลักที่คุณอยากเริ่มดูแลตอนนี้คืออะไร?', options:['ลดไขมัน / ดูแลรูปร่าง','ปรับพฤติกรรมการกิน','เพิ่มพลังงานในชีวิตประจำวัน','สร้าง Lifestyle ที่ดีขึ้น','ดูแลสุขภาพระยะยาว'] },
  { id:'q2', category:'PAIN_POINT', text:'ตอนนี้เรื่องไหนเป็นอุปสรรคของคุณมากที่สุด?', options:['พุงหรือรูปร่างเปลี่ยน','น้ำหนักขึ้นง่าย','กินจุกจิก / คุมอาหารยาก','ไม่มีเวลา','เริ่มแล้วทำต่อไม่ต่อเนื่อง','ไม่รู้ว่าจะเริ่มอย่างไร'] },
  { id:'q3', category:'BEHAVIOR', text:'พฤติกรรมไหนเกิดขึ้นกับคุณบ่อยที่สุด?', options:['กินมื้อดึก','เครื่องดื่มหวาน','ของทอด / ของมัน','กินนอกบ้านบ่อย','รู้สึกว่าโปรตีนหรือผักไม่พอ','นั่งนาน / เคลื่อนไหวน้อย'] },
  { id:'q4', category:'BEHAVIOR', text:'โดยทั่วไปคุณจัดมื้ออาหารได้สม่ำเสมอแค่ไหน?', options:['สม่ำเสมอมาก','ค่อนข้างสม่ำเสมอ','บางวันทำได้ บางวันไม่ได้','ไม่ค่อยสม่ำเสมอ'] },
  { id:'q5', category:'BEHAVIOR', text:'การนอนและการพักผ่อนของคุณช่วงนี้เป็นอย่างไร?', options:['ค่อนข้างดี','พอใช้','น้อยหรือไม่เป็นเวลา','ยังจัดการไม่ได้'] },
  { id:'q6', category:'READINESS', text:'ถ้าเลือกเปลี่ยนได้ 1 เรื่องใน 7 วันข้างหน้า คุณพร้อมแค่ไหน?', scale:true },
  { id:'q7', category:'READINESS', text:'อะไรจะช่วยให้คุณทำต่อเนื่องได้ง่ายขึ้น?', options:['มีแผนที่ชัดเจน','มีคนช่วยติดตาม','มีวิธีที่ง่ายและใช้เวลาน้อย','เห็นความก้าวหน้าของตัวเอง','ยังไม่แน่ใจ'] },
  { id:'q8', category:'GOAL', text:'คุณอยากได้รับความช่วยเหลือแบบไหนมากที่สุด?', options:['แนวทางเริ่มต้นแบบง่าย','คำแนะนำเฉพาะตัว','แผน 7 วัน','คนช่วยติดตามต่อเนื่อง','อยากคุยกับผู้เชี่ยวชาญ'] },
];

function getSessionId(){ const key='vr_session_id'; const old=localStorage.getItem(key); if(old) return old; const id=crypto.randomUUID(); localStorage.setItem(key,id); return id; }
function getAttribution(){ const p=new URLSearchParams(window.location.search); const keys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term']; const a:any={}; keys.forEach(k=>a[k]=p.get(k)||localStorage.getItem(k)||''); keys.forEach(k=>{ if(p.get(k)) localStorage.setItem(k,p.get(k)!); }); return a; }
function event(name:string, value:any={}){ const key='vr_event_queue'; const list=JSON.parse(localStorage.getItem(key)||'[]'); const e={event_id:crypto.randomUUID(),event_name:name,timestamp:new Date().toISOString(),session_id:getSessionId(),...value}; localStorage.setItem(key,JSON.stringify([...list,e])); }

export default function Home(){
  const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [answers,setAnswers]=useState<Record<string,string>>({});
  const [capture,setCapture]=useState(false); const [result,setResult]=useState(false); const [nickname,setNickname]=useState(''); const [line,setLine]=useState(''); const [email,setEmail]=useState(''); const [age,setAge]=useState(''); const [serviceConsent,setServiceConsent]=useState(false); const [marketing,setMarketing]=useState(false); const [session,setSession]=useState('');
  useEffect(()=>{ const s=getSessionId(); setSession(s); event('PAGE_VIEW'); const saved=localStorage.getItem('vr_quiz_state'); if(saved){ const x=JSON.parse(saved); setStarted(x.started); setStep(x.step||0); setAnswers(x.answers||{}); } },[]);
  useEffect(()=>{ if(started&&!result) localStorage.setItem('vr_quiz_state',JSON.stringify({started,step,answers})); },[started,step,answers,result]);
  const q=questions[step];
  const leadId=useMemo(()=>{ if(typeof window==='undefined') return ''; const k='vr_lead_id'; const old=localStorage.getItem(k); if(old)return old; const d=new Date(); const date=d.toISOString().slice(0,10).replaceAll('-',''); const id=`VR-${date}-00001`; localStorage.setItem(k,id); return id; },[]);
  function start(){setStarted(true); event('QUIZ_START'); event('QUESTION_VIEW',{question_id:q.id});}
  function answer(v:string){ setAnswers(a=>({...a,[q.id]:v})); event('QUESTION_ANSWER',{question_id:q.id,answer:v}); if(step<questions.length-1){ const next=step+1; setStep(next); event('QUESTION_VIEW',{question_id:questions[next].id}); } else { event('QUIZ_COMPLETE',{lead_id:leadId}); setCapture(true); } }
  function submit(){ if(!nickname.trim()||!line.trim()||!serviceConsent)return; const a=getAttribution(); localStorage.setItem('vr_lead',JSON.stringify({lead_id:leadId,nickname,line,email,age,serviceConsent,marketing,consent_version:'v1',privacy_policy_version:'v1',consent_timestamp:new Date().toISOString(),session_id:session,...a,answers})); event('REPORT_REQUEST',{lead_id:leadId}); setCapture(false); setResult(true); event('RESULT_VIEW',{lead_id:leadId}); }
  const profile=answers.q1?.includes('ลด')?'พร้อมเริ่ม แต่ต้องการระบบที่ทำต่อเนื่องได้':answers.q2?.includes('ต่อเนื่อง')?'เริ่มหลายครั้งแต่ทำต่อไม่ต่อเนื่อง':'ต้องการจุดเริ่มต้นที่ง่ายและทำได้จริง';
  if(result) return <main className="page"><section className="card result"><span className="eyebrow">VREasyHealthy • Personal Insight</span><h1>คุณอยู่ในกลุ่ม</h1><h2>{profile}</h2><p>จากคำตอบของคุณ นี่คือแนวโน้มและพฤติกรรมที่ควรใส่ใจเบื้องต้น ไม่ใช่การวินิจฉัยทางการแพทย์</p><div className="grid"><div><b>สิ่งที่ควรเริ่มก่อน</b><ol><li>เลือกเปลี่ยน 1 พฤติกรรมที่ทำได้จริง</li><li>จัดมื้ออาหารให้มีโครงสร้างง่ายขึ้น</li><li>ติดตามความสม่ำเสมอแทนการเอาตัวเลขมาตัดสินตัวเอง</li></ol></div><div><b>สิ่งที่ควรหลีกเลี่ยง</b><ol><li>เปลี่ยนทุกอย่างพร้อมกัน</li><li>ใช้ความรู้สึกผิดเป็นแรงผลัก</li><li>ตั้งเป้าหมายที่ทำไม่ได้ในชีวิตจริง</li></ol></div></div><button onClick={()=>{event('LINE_CLICK',{lead_id:leadId}); window.location.href='https://line.me/';}}>รับรายงานส่วนตัวฟรีทาง LINE</button><small>Lead ID: {leadId}</small></section></main>;
  if(capture) return <main className="page"><section className="card"><span className="eyebrow">เกือบเสร็จแล้ว</span><h1>ขอข้อมูลเล็กน้อยเพื่อแสดงผลส่วนตัว</h1><input placeholder="ชื่อเล่น" value={nickname} onChange={e=>setNickname(e.target.value)}/><input placeholder="LINE ID / ช่องทางติดต่อ" value={line} onChange={e=>setLine(e.target.value)}/><input placeholder="Email (ถ้าสะดวก)" value={email} onChange={e=>setEmail(e.target.value)}/><select value={age} onChange={e=>setAge(e.target.value)}><option value="">อายุเป็นช่วง</option><option>18–24</option><option>25–34</option><option>35–44</option><option>45–54</option><option>55+</option></select><label className="check"><input type="checkbox" checked={serviceConsent} onChange={e=>setServiceConsent(e.target.checked)}/> ยินยอมให้ VREasyHealthy เก็บและใช้ข้อมูลเพื่อจัดทำผลประเมินและติดต่อกลับเกี่ยวกับบริการ</label><label className="check"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/> ยินยอมรับข่าวสาร โปรโมชั่น และเนื้อหาด้านสุขภาพ</label><button disabled={!nickname.trim()||!line.trim()||!serviceConsent} onClick={submit}>ดูผลประเมิน</button><small>Marketing consent เป็นตัวเลือกและไม่จำเป็นต่อการรับผลประเมิน</small></section></main>;
  if(started) return <main className="page"><section className="card quiz"><div className="progress"><span>คำถาม {step+1} / {questions.length}</span><div><i style={{width:`${((step+1)/questions.length)*100}%`}}/></div></div><span className="eyebrow">{q.category}</span><h1>{q.text}</h1>{q.scale?<div className="scale">{Array.from({length:10},(_,i)=><button key={i} onClick={()=>answer(String(i+1))}>{i+1}</button>)}</div>:<div className="options">{q.options?.map(o=><button key={o} onClick={()=>answer(o)}>{o}</button>)}</div>}<button className="back" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}>ย้อนกลับ</button></section></main>;
  return <main className="page"><section className="hero"><span className="eyebrow">VREasyHealthy • Easy Healthy Life</span><h1>คุณกำลังดูแลสุขภาพ<br/>ถูกจุดหรือยัง?</h1><p>ทำแบบประเมินสั้น ๆ 2 นาที เพื่อดูว่าคุณควรเริ่มปรับอะไรเป็นอันดับแรก</p><button onClick={start}>เริ่มประเมินฟรี</button></section><section className="section"><h2>บางครั้งปัญหาไม่ได้อยู่ที่วินัย</h2><p>แต่อยู่ที่ระบบที่เราใช้ เราจึงออกแบบแบบประเมินให้ช่วยคุณเห็น “จุดเริ่มต้น” ที่เหมาะกับชีวิตจริง</p><div className="grid three"><article><b>เห็นตัวเองชัดขึ้น</b><p>เข้าใจเป้าหมายและพฤติกรรมของตัวเอง</p></article><article><b>เริ่มทีละเรื่อง</b><p>เลือกสิ่งที่ทำได้จริงก่อน ไม่ต้องเปลี่ยนทุกอย่าง</p></article><article><b>มี Next Step</b><p>รู้ว่าหลังจากเริ่มแล้วควรเดินต่ออย่างไร</p></article></div></section><section className="section light"><h2>ใช้เวลาประมาณ 2 นาที</h2><p>8 คำถาม • ไม่มีคำตอบถูกหรือผิด • ผลเป็นแนวทางเบื้องต้น</p><button className="secondary" onClick={start}>เริ่มประเมินฟรี</button></section><footer>© VREasyHealthy • Privacy Policy • Terms</footer></main>
}
